# Generated by Django 4.1.5 on 2023-01-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_pledge_supporter_pledge_supporter_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='liked_by',
        ),
    ]
